### ISSUE TITLE
[Bug]: Multiple values in the function field result in empty response

### ISSUE THREAD

**Issue by SkullElf** [multiversx/mx-api-service#1018]
### Description

Entering a list of values in the function field of the /transactions endpoint results in an empty list of transactions after recent changes to the ES cluster's settings

### Steps to reproduce

Works:
https://api.multiversx.com/transactions?receiver=erd1qqqqqqqqqqqqqpgqd9rvv2n378e27jcts8vfwynpx0gfl5ufz6hqhfy0u0,erd1qqqqqqqqqqqqqpgq6wegs2xkypfpync8mn2sa5cmpqjlvrhwz5nqgepyg8,erd1qqqqqqqqqqqqqpgq705fxpfrjne0tl3ece0rrspykq88mynn4kxs2cg43s&function=listing

Doesn't work:
https://api.multiversx.com/transactions?receiver=erd1qqqqqqqqqqqqqpgqd9rvv2n378e27jcts8vfwynpx0gfl5ufz6hqhfy0u0,erd1qqqqqqqqqqqqqpgq6wegs2xkypfpync8mn2sa5cmpqjlvrhwz5nqgepyg8,erd1qqqqqqqqqqqqqpgq705fxpfrjne0tl3ece0rrspykq88mynn4kxs2cg43s&function=listing,auctionToken

### On which network is the bug manifesting itself?

Mainnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by schimih** [comment]
Hey @SkullElf 

this has been solved in the meantime. Please open the issue again if problem still persists.
