### ISSUE TITLE
How can I configure to reindex the history blocks info?

### ISSUE THREAD

**Issue by sylviahuang123** [multiversx/mx-api-service#1169]
I can only query the latest blocks info from api after I configure Elasticsearch, are there any way to reindex the blocks before?

**Comment by bogdan-rosianu** [comment]
Hi. This isn't related to the api service, but rather to populating the Elasticsearch cluster. You can read the documentation here: https://docs.multiversx.com/sdk-and-tools/elastic-search/#clone-an-elasticsearch-cluster
