### ISSUE TITLE
[Bug]:  Sockets in configs are obsolete 

### ISSUE THREAD

**Issue by IosifGabriel** [multiversx/mx-api-service#1317]
### Contact Details

gabriel.iosif@buidly.com

### Description

Sockets in configs are obsolete 

### Steps to reproduce

Had to change to {"url":"socket-api-ams.multiversx.com"} in my configs 

### On which network is the bug manifesting itself?

Mainnet, Devnet, Testnet

### Relevant log output

```shell
Access to XMLHttpRequest at 'https://socket-fra.elrond.com/socket.io/?' from origin 'xxx' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.


in any dapp which uses a private api
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IosifGabriel** [comment]
This wrong config for sockets affects the toaster and wont query the /transactions endpoint to see if any tx was finished

**Comment by bogdan-rosianu** [comment]
Hello. Thanks for raising this. I have made the required updates in #1318

**Comment by IosifGabriel** [comment]
Thanks @bogdan-rosianu!
