### ISSUE TITLE
[Bug]: Referral API calls

### ISSUE THREAD

**Issue by matt1elrond** [multiversx/mx-api-service#757]
### Contact Details

mattfi4567@gmail.com

### Description

On Referral page two calls to the API seem to be failing

### Steps to reproduce

Go to https://get.maiar.com/referral/some-referral-string

Look in inspector - 
- POST https://api.elrond.com/country 404 (on page load)
-  POST https://get.maiar.com/api/referral 503 (on attempting to sign up)

Using chrome but seems to be an issue in other browsers too.

### On which network is the bug manifesting itself?

Mainnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanghel** [comment]
Hello!

We have discussed internally and will address both issues.

Will close this issue once it's done
