### ISSUE TITLE
[Bug]: https://devnet-api.elrond.com/tokens?identifiers=USDC-05bdcc returns wrong ticker

### ISSUE THREAD

**Issue by icegriffinguru** [multiversx/mx-api-service#924]
### Description

https://devnet-api.elrond.com/tokens?identifiers=USDC-05bdcc returns wrong ticker

### Steps to reproduce

result
```
[
    {
        "type": "FungibleESDT",
        "identifier": "USDC-05bdcc",
        "name": "USDC",
        "ticker": "USDC-05bdcc",
        "owner": "erd1r69gk66fmedhhcg24g2c5kn2f2a5k4kvpr6jfw67dn2lyydd8cfswy6ede",
        "decimals": 6,
        "isPaused": false,
        "transactions": 10,
        "accounts": 3,
        "canUpgrade": true,
        "canMint": true,
        "canBurn": true,
        "canChangeOwner": true,
        "canPause": true,
        "canFreeze": true,
        "canWipe": true
    }
]
```

### On which network is the bug manifesting itself?

Devnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanghel** [comment]
The ticker will be returned in a simple manner only if the token has assets defined here: https://github.com/multiversx/mx-assets

This is not a bug, it is intended functionality to differentiate between "supported" tokens and "unsupported" tokens which might be spam / scam

**Comment by icegriffinguru** [comment]
> The ticker will be returned in a simple manner only if the token has assets defined here: https://github.com/multiversx/mx-assets
> 
> This is not a bug, it is intended functionality to differentiate between "supported" tokens and "unsupported" tokens which might be spam / scam

How can other devs or people know it was intended or not?
Can you add "supported" or "registered" flag to show it instead of breaking ticker?
