### ISSUE TITLE
[Bug]: No decimal point in acconuts/{address}/transactions api response

### ISSUE THREAD

**Issue by dylanzxc** [multiversx/mx-api-service#943]
### Description

There is no decimal point in most of the api response, such as balance and transaction values. How can I determine the actual value?

### Steps to reproduce

curl -X 'GET' \
  'https://api.multiversx.com/accounts/erd1rm8pg3yrngzyhrjejkz3xq2lfp64mvnt64llj3fyft53d3t4ckjq0q8v4k/transactions?after=1672358400&withScResults=true&computeScamInfo=true' \
  -H 'accept: application/json'

### On which network is the bug manifesting itself?

Mainnet

### Relevant log output

```shell
{
    "txHash": "15501cc89d5e2db7afc9fe9748843fcee22518ae9513c8e16354a216b34dc41d",
    "gasLimit": 50000,
    "gasPrice": 1000000000,
    "gasUsed": 50000,
    "miniBlockHash": "c9aa32f24422a1f1fd2398ca1f7945c581773b5a124334cf16db8c25dac2fcdd",
    "nonce": 1,
    "receiver": "erd1rm8pg3yrngzyhrjejkz3xq2lfp64mvnt64llj3fyft53d3t4ckjq0q8v4k",
    "receiverAssets": {
      "name": "Exchange: Binance.us",
      "tags": [
        "binance",
        "exchange"
      ],
      "iconPng": "https://raw.githubusercontent.com/multiversx/mx-assets/master/accounts/icons/binance.png",
      "iconSvg": "https://raw.githubusercontent.com/multiversx/mx-assets/master/accounts/icons/binance.svg"
    },
    "receiverShard": 0,
    "round": 13066215,
    "sender": "erd1qyckqpf7x6znk4s0336az5mree4vhdma5fueczg0skqrwqe4pltqs09alf",
    "senderShard": 2,
    "signature": "d2a1eb37038d9f54e926c0a1cb02816d9ed1e2d89003942a80a41b75d32e921010faa4f9a4edd6d6d617363b8620a97d77737f24056499fe38b5fe150a634e01",
    "status": "success",
    "value": "37456619510000000000",
    "fee": "50000000000000",
    "timestamp": 1674514890
  }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanghel** [comment]
Hello!

This is intended functionality, the value `37456619510000000000` is denominated with 18 decimal points. By dividing with 10^18, you should get 37.45661951 eGLD

The reason why we represent it this way is because floating point numbers are inherently imprecise. This allows us to work with perfect precision if mathematical operations are done with BigInts or equivalents
